apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-learning-frontend
  template:
    metadata:
      labels:
        app: e-learning-frontend
    spec:
      containers:
      - name: e-learning-frontend
        image: geraldrandriamanantena/e-learning-frontend:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: LoadBalancer
  selector:
    app: e-learning-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
