apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: frontY4OKHnOWwo2zeeB2/qt4WL9s8dsRPlvrhX4BB3x4
    spec:
      containers:
      - name: front
        image: devcloudarmel/front:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: LoadBalancer
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
