name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push backend Docker image to Docker Hub
    - name: Build, tag, and push backend Docker image to Docker Hub
      env:
        BACKEND_IMAGE_NAME: geraldrandriamanantena/e-learning-backend
        IMAGE_TAG: latest
      run: |
        docker build -t $BACKEND_IMAGE_NAME:$IMAGE_TAG ./backend-laravel
        docker push $BACKEND_IMAGE_NAME:$IMAGE_TAG

    # Step 4: Configure AWS credentials for EC2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: af-south-1

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: "13.247.80.4"  # IP de l'instance EC2
        username: "ubuntu"  # Assurez-vous que c'est l'utilisateur correct
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          docker pull geraldrandriamanantena/e-learning-backend:latest
          docker run -d --name backend_new -p 80:80 geraldrandriamanantena/e-learning-backend:latest
          sleep 10
          if [ "$(docker inspect -f '{{.State.Running}}' backend_new)" = "true" ]; then
            docker stop backend || true
            docker rm backend || true
            
            docker rename backend_new backend
          else
            echo "Deployment failed. New container did not start properly."
            exit 1
          fi